addi                    PASSED
add                     PASSED
andi                    PASSED
and                     PASSED
auipc                   PASSED
beq                     PASSED
bge                     PASSED
bgeu                    PASSED
blt                     PASSED
bltu                    PASSED
bne                     PASSED
chenillard_minimaliste  PASSED
chenillard_rotation     PASSED
compteur                PASSED
csrrci                  PASSED
csrrc                   PASSED
csrrsi                  PASSED
csrrs                   PASSED
csrrwi                  PASSED
csrrw                   PASSED
jalr                    PASSED
jal                     PASSED
lb                      PASSED
lbu                     PASSED
lh                      PASSED
lhu                     PASSED
lui                     PASSED
lw                      PASSED
mret                    PASSED
ori                     PASSED
or                      PASSED
rebouclage              PASSED
sb                      PASSED
sh                      PASSED
slli                    PASSED
sll                     PASSED
slti                    PASSED
sltiu                   PASSED
slt                     PASSED
sltu                    PASSED
srai                    PASSED
sra                     PASSED
srli                    PASSED
srl                     PASSED
sub                     PASSED
sw                      PASSED
xori                    PASSED
xor                     PASSED
